spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}

server:
  port: 8082


swagger:
  # 部署时间 yyyy-MM-dd HH:mm:ss
  publishDate:
  enable: true
  active: ${spring.profiles.active}
  basePackage: com.study.controller
  title: 消费者
  description: 消费者微服务
  termsOfServiceUrl: http://www.consumer.com
  version: 1.0