spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}

server:
  port: 8081

swagger:
  # 部署时间 yyyy-MM-dd HH:mm:ss
  publishDate:
  active: ${spring.profiles.active}
  basePackage: com.study.controller
  title: 生产者
  description: 生产者微服务
  termsOfServiceUrl: http://www.provider.com
  version: 1.0

knife4j:
  # 是否屏蔽Swagger
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: zhangsan
    password: 123